### ISSUE TITLE
Error installing Megadepth

### ISSUE THREAD

**Issue by shmenolin** [ChristopherWilks/megadepth#13]
I got the following error while installing Megadepth. Could you please help me solve these issues?

Thank you

```
> library(megadepth)
> megadepth_cmd()
Error: megadepth not found. You can install it via megadepth::install_megadepth()
> megadepth::install_megadepth()
Error in file(con, "r") : 
  cannot open the connection to 'https://github.com/ChristopherWilks/megadepth/releases/latest'
In addition: Warning message:
In file(con, "r") :
  URL 'https://github.com/ChristopherWilks/megadepth/releases/latest': Timeout of 60 seconds was reached
```

**Comment by ChristopherWilks** [comment]
Hi @shmenolin,
Thanks for the detailed issue report.

I just tried this myself (via sudo on a machine I have R on) and it worked for me so I suspect it's either a transient connection issue with github or an issue with your specific system/network.  So I suggest you try it again and/or try a different system if you have one.

I don't maintain the R megadepth package, just the binary here, so for further issues with the R megadepth package I'd suggest you'd post to bioconductor support site as stated here:
https://bioconductor.org/packages/release/bioc/vignettes/megadepth/inst/doc/megadepth.html#13_Asking_for_help

Thanks,
Chris
