### ISSUE TITLE
segmentation failure on a big endian (s390) platform

### ISSUE THREAD

**Issue by mdb571** [ChristopherWilks/megadepth#14]
While running the tests on s390 I'm getting the following error

```
building whole annotation region map done
2 chromosomes for annotated regions read
0 chromosomes for annotated regions read, collapsed
total number of annotations in collapsed: 0
Processing BAM: "tests/test_noprefix.bam"
/tmp/autopkgtest-lxc.gmfzuwos/downtmp/build.jJn/src/debian/tests/run-unit-test: line 33:  1590 Segmentation fault      megadepth tests/test_noprefix.bam --prefix test.bam --threads 4 --bigwig --auc --min-unique-qual 10 --annotation tests/test_exons.bed --frag-dist --alts --include-softclip --only-polya --read-ends --test-polya --no-annotation-stdout --no-auc-stdout --filter-out 260 --add-chr-prefix human
```

**Comment by ChristopherWilks** [comment]
Thanks for your interest in Megadepth.

Architectural compatibility outside of x86_64 is beyond my scope of maintenance as Megadepth is no longer part of my day-to-day development job and the existing implemtation+binaries appear to work for most of my target audience.  I am willing to review others' PR's if they're motivated to patch the code for a specific architecture.

That said, I am curious as to what you're doing here. It looks like this message was from an automated build process of some kind, would you be willing to provide a bit more context?

**Comment by mdb571** [comment]
Yeah sure. This is done as part of Debian's automatic build process which automatically builds the package for various architectures. Currently we have a bug report[1] for megadepth regarding this failure.

Thanks for your quick response and i think the best we can do here is to skip the tests for s390.

[1] - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016454

**Comment by ChristopherWilks** [comment]
oh cool! I hadn't realized there was a Debian package for Megadepth.  Thanks for doing that!
I also think that skipping the s390 is reasonable given Megadepth's intended audience aren't likely to be running on those machines anyway.
